spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./u2-bot.db
    username:
    password:

mybatis:
  mapper-locations: mapper/*Mapper.xml

user:
  id:

bot:
  token: ${BOT_TOKEN}
  username: ${BOT_NAME}
  proxy:
    host: ${PROXY_HOST}
    port: ${PROXY_PORT}
    type: ${PROXY_TYPE} #SOCKS4 | SOCKS5 | HTTP

u2:
  domain: https://u2.dmhy.org
  cookie:

phantomjs:


#logging:
#  level:
#    root: debug
